name: deploy 
on:
  workflow_dispatch: 
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 2,4,6'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check branch
        uses: actions/checkout@v4
      
      - name: Git config
        run: |
          git config --global user.name "jygzyc"
          git config --global user.email "jyg.zyc@outlook.com"
      - name: Git pull
        run: git pull

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
    
      - name: Install requirements
        run: pip install requests python-slugify pytz

