name: deploy 
on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check branch
        uses: actions/checkout@v4
      
      - name: Git config
        run: |
          git config --global user.name "CloveIso"
          git config --global user.email "1258511864@qq.com"
      - name: Git pull
        run: git pull

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
    
      - name: Install requirements
        run: pip install requests python-slugify pytz

    
      - name: Commit files
        run: |
          current="`TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S'`"
          message="Add Changes By GitHub Actions: $current (CST/UTC-8)"
          echo "$message" > update.log          
          git add --all
          git commit -a -m "$message"
        
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with: 
            github_token: ${{ secrets.PERSONAL_NOTE_ACCESS_TOKEN }}
            branch: main

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${ env.cache_id }
          path: .cache
          restore-keys: |
            mkdocs-material-

      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force

