name: deploy 
on:
  push:
    branches: [ main ]

permissions:
    contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     python-version: [3.11]
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${ env.cache_id }
          path: .cache
          restore-keys: |
            mkdocs-material-

      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-glightbox
      - run: pip install mkdocs-minify-plugin
      - run: pip install jieba 
      - run: pip install mkdocs-redirects
      - run: pip install mkdocs-awesome-pages-plugin

      - run: pip install --upgrade mkdocs-material
      - run: mkdocs gh-deploy --force

